version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ../../warp:/go/src/app
      - /go/src/app/.dev/
    tty: true
    working_dir: /go/src/app
