---
- hosts: warp
  remote_user: root

  tasks:
  - name: apt update
    apt:
      update_cache: yes

  # nginx
  - name: ensure nginx and certbot is at the latest version
    apt:
      name: nginx
      state: latest
  - name: ensure that nginx is started
    service:
      name: nginx
      state: started
      enabled: yes

  # certbot
  - name: ensure certbot is at the latest version
    apt:
      name: "{{ package }}"
      state: latest
    vars:
      package:
        - certbot
        - python3-certbot-ngnx
    when: target == 'prod'
  - name: obtains cert keys
    command: certbot --nginx -d hngex.email -d www.hngex.email -d mx.hngex.email -m linyows@gmail.com --agree-tos --keep-until-expiring --non-interactive
    when: target == 'prod'
  - name: ensure that certbot.timer is started
    service:
      name: certbot.timer
      state: started
    when: target == 'prod'

  # postfix
  - name: ensure postfix is at the latest version
    apt:
      name: postfix
      state: latest
  - name: write the postfix main config file
    template:
      src: ./etc/postfix/main.cf
      dest: /etc/postfix/main.cf
  - name: write the postfix master config file
    template:
      src: ./etc/postfix/master.cf
      dest: /etc/postfix/master.cf
    notify:
      - restart postfix
  - name: ensure that postfix is started
    service:
      name: postfix
      state: started
      enabled: yes

  # postsrsd
  - name: ensure postsrsd is at the latest version
    apt:
      name: postsrsd
      state: latest
  - name: ensure that postsrsd is started
    service:
      name: postsrsd
      state: started
      enabled: yes

  # dovecot
  - name: ensure dovecot is at the latest version
    apt:
      name: "{{ package }}"
      state: latest
    vars:
      package:
        - dovecot-core
        - dovecot-imapd
        - dovecot-pop3d
  - name: create users by doveadm
    command: >
      echo "{{ email1 }}:`doveadm pw -s CRAM-MD5 -p {{ pw1 }}`" >> /etc/dovecot/users
      echo "{{ email2 }}:`doveadm pw -s CRAM-MD5 -p {{ pw2 }}`" >> /etc/dovecot/users
    notify: restart dovecot
  - name: write the dovecot auth config file
    template:
      src: ./etc/dovecot/conf.d/10-auth.conf
      dest: /etc/dovecot/conf.d/10-auth.conf
  - name: write the dovecot mail config file
    template:
      src: ./etc/dovecot/conf.d/10-mail.conf
      dest: /etc/dovecot/conf.d/10-mail.conf
  - name: write the dovecot master config file
    template:
      src: ./etc/dovecot/conf.d/10-master.conf
      dest: /etc/dovecot/conf.d/10-master.conf
  - name: write the dovecot ssl config file
    template:
      src: ./etc/dovecot/conf.d/10-ssl.conf
      dest: /etc/dovecot/conf.d/10-ssl.conf
  - name: write the dovecot submission config file
    template:
      src: ./etc/dovecot/conf.d/20-submission.conf
      dest: /etc/dovecot/conf.d/20-submission.conf
  - name: write the dovecot passwdfile config file
    template:
      src: ./etc/dovecot/conf.d/auth-passwdfile.conf.ext
      dest: /etc/dovecot/conf.d/auth-passwdfile.conf.ext
  - name: write the dovecot static config file
    template:
      src: ./etc/dovecot/conf.d/auth-static.conf.ext
      dest: /etc/dovecot/conf.d/auth-static.conf.ext
    notify:
      - restart dovecot
  - name: ensure that dovecot is started
    service:
      name: dovecot
      state: started
      enabled: yes

  # mysql
  - name: ensure mysql-server is at the latest version
    apt:
      name: mysql-server
      state: latest
  - name: ensure that mysql is started
    service:
      name: mysql
      state: started
      enabled: yes
